const PROJECT_IMAGE = 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800&auto=format&fit=crop&q=80';

export const PROJECTS = [
  {
    title: 'ML Feature Store Platform',
    description: 'Company-wide ML Feature Store built from scratch at iFood (80% of Brazilian food delivery market, 320K restaurants, 100 ML models in production) — the central data layer serving 17+ squads across fraud, recommendations, logistics, and fintech. Featured as a Redis Cloud customer case study.',
    input: 'Kafka, Delta Lake',
    throughput: '200+ concurrent Spark jobs',
    latency: '< 20ms P99',
    status: 'Production · Redis Case Study',
    stack: ['Scala', 'Java', 'Python', 'Go', 'Apache Spark', 'Apache Kafka', 'Delta Lake', 'Redis', 'PostgreSQL', 'Kubernetes', 'AWS (EKS, S3, SNS)', 'Databricks', 'Terraform'],
    image: PROJECT_IMAGE,
    overview: 'Built from scratch at iFood — Brazil\'s largest food delivery platform with 80% market share, 320,000 restaurants, and 100 ML models in production. The Feature Store became the central ML data layer serving 17+ squads across fraud, recommendations, logistics, and fintech. The platform runs 200+ concurrent Spark jobs processing petabytes of data daily, with online serving at under 20ms p99 latency. Featured in the official Redis Cloud customer case study. The platform unified three latency tiers under a single aggregation model: real-time (sub-second, Kafka to Redis), near-real-time (Spark Structured Streaming with RocksDB exactly-once recovery), and batch. Materialization targets are fully decoupled — Redis Enterprise Cloud for online serving, Delta Lake for offline training with point-in-time correctness, and Kafka for event-driven consumers.',
    challenges: [
      'Supporting three latency tiers (batch, near-real-time, real-time) under a single aggregation model',
      'Guaranteeing exactly-once processing in Spark Structured Streaming via RocksDB checkpoints',
      'Achieving point-in-time correctness for offline training data to prevent label leakage',
      'Coordinating feature lifecycle across 17+ squads with automated CI/CD and domain-owner approval routing',
      'Attributing Redis and compute cost per feature and per consuming squad for chargeback',
    ],
    outcomes: [
      { value: '320K', label: 'Restaurants on platform' },
      { value: '100', label: 'ML models in production' },
      { value: '80%', label: 'Brazilian food delivery market' },
      { value: '200+', label: 'Concurrent Spark jobs' },
      { value: '< 20ms', label: 'P99 online serving' },
      { value: '17+', label: 'ML squads served' },
    ],
    nodes: [
      { x: 10, y: 15, label: 'IaC', w: 30 },
      { x: 10, y: 45, label: 'Mega', w: 30 },
      { x: 55, y: 30, label: 'Spark', w: 30 },
      { x: 100, y: 15, label: 'Redis', w: 25 },
      { x: 100, y: 45, label: 'Delta', w: 25 },
      { x: 145, y: 30, label: 'Go API', w: 30 },
    ],
    edges: [
      { x1: 40, y1: 22, x2: 55, y2: 37 },
      { x1: 40, y1: 52, x2: 55, y2: 37 },
      { x1: 85, y1: 37, x2: 100, y2: 22 },
      { x1: 85, y1: 37, x2: 100, y2: 52 },
      { x1: 125, y1: 22, x2: 145, y2: 37 },
      { x1: 125, y1: 52, x2: 145, y2: 37 },
    ],
    diagram: {
      groups: [
        { x: 5, y: 20, w: 120, h: 260, label: 'DECLARATION' },
        { x: 135, y: 20, w: 110, h: 260, label: 'SOURCES' },
        { x: 255, y: 20, w: 130, h: 260, label: 'AGGREGATION ENGINE' },
        { x: 395, y: 20, w: 110, h: 260, label: 'MATERIALIZERS' },
        { x: 515, y: 20, w: 120, h: 260, label: 'STORAGE' },
        { x: 645, y: 20, w: 145, h: 260, label: 'CONSUMERS · 17+ SQUADS' },
      ],
      nodes: [
        { x: 15, y: 60, w: 100, h: 30, label: 'Features IaC', sublabel: 'Git + CI/CD' },
        { x: 15, y: 120, w: 100, h: 30, label: 'Megamentos', sublabel: 'Control Plane' },
        { x: 145, y: 60, w: 90, h: 30, label: 'Kafka', sublabel: 'Streaming' },
        { x: 145, y: 120, w: 90, h: 30, label: 'Delta Tables', sublabel: 'Data Lake' },
        { x: 265, y: 60, w: 110, h: 35, label: 'Two-Step Agg', sublabel: 'Batch · NRT · RT' },
        { x: 265, y: 140, w: 110, h: 35, label: 'Delta Bus', sublabel: 'Transactional' },
        { x: 405, y: 50, w: 90, h: 28, label: 'Kafka Mat.', sublabel: '' },
        { x: 405, y: 110, w: 90, h: 28, label: 'Redis Mat.', sublabel: '' },
        { x: 405, y: 170, w: 90, h: 28, label: 'Delta Mat.', sublabel: '' },
        { x: 525, y: 50, w: 100, h: 28, label: 'Kafka Topics', sublabel: 'output' },
        { x: 525, y: 110, w: 100, h: 28, label: 'Redis', sublabel: '< 20ms p99' },
        { x: 525, y: 170, w: 100, h: 28, label: 'Delta Lake', sublabel: 'Historical' },
        { x: 655, y: 80, w: 125, h: 35, label: 'Online API', sublabel: 'Go · 800 pods' },
        { x: 655, y: 160, w: 125, h: 35, label: 'Offline Serving', sublabel: 'Model training' },
      ],
      edges: [
        { x1: 65, y1: 90, x2: 65, y2: 120, label: '' },
        { x1: 115, y1: 135, x2: 265, y2: 77, label: 'provision' },
        { x1: 235, y1: 75, x2: 265, y2: 75, label: '' },
        { x1: 235, y1: 135, x2: 265, y2: 82, label: '' },
        { x1: 320, y1: 95, x2: 320, y2: 140, label: '' },
        { x1: 375, y1: 155, x2: 405, y2: 64, label: '' },
        { x1: 375, y1: 157, x2: 405, y2: 124, label: '' },
        { x1: 375, y1: 160, x2: 405, y2: 184, label: '' },
        { x1: 495, y1: 64, x2: 525, y2: 64, label: '' },
        { x1: 495, y1: 124, x2: 525, y2: 124, label: '' },
        { x1: 495, y1: 184, x2: 525, y2: 184, label: '' },
        { x1: 625, y1: 64, x2: 655, y2: 97, label: '' },
        { x1: 625, y1: 124, x2: 655, y2: 100, label: '' },
        { x1: 625, y1: 184, x2: 655, y2: 177, label: '' },
      ],
    },
  },
  {
    title: 'MadeiraMadeira — Scalable Airflow on AWS ECS Fargate',
    description: 'Full re-architecture of MadeiraMadeira\'s Airflow platform, decomposing every component into isolated ECS Fargate containers with ephemeral per-DAG-run execution — delivering 60%+ cost reduction and a self-service DAG factory that cut pipeline creation time from 7 days to 3.',
    input: 'Git (Python/YAML)',
    throughput: 'Ephemeral per DAG',
    latency: 'Auto-scaling',
    status: 'Production',
    stack: ['Apache Airflow', 'AWS ECS Fargate', 'EFS', 'RDS PostgreSQL', 'SQS', 'DynamoDB', 'Celery', 'Docker', 'Terraform'],
    image: PROJECT_IMAGE,
    overview: 'A full re-architecture of a legacy Apache Airflow deployment that was running every component — scheduler, webserver, workers, and all DAG executions — on a single EC2 instance. The machine crashed weekly under concurrent load and required constant manual intervention to scale. The solution decomposed every Airflow component into its own isolated ECS Fargate container, with each DAG run spawning a dedicated ephemeral container that is torn down after execution. The result was over 60% cost reduction, zero resource contention between concurrent executions, and a platform that scales automatically. Alongside the infrastructure change, a DAG factory was introduced. Since the primary use case was running ETL/ELT Python scripts on a schedule, engineers and analysts no longer needed to write Airflow Python code — they fill in a YAML file and the factory generates the DAG automatically. This reduced the time to create a new pipeline from 7 days to 3 days. The platform is composed of nine interconnected components: the Scheduler (a dedicated Fargate container reading DAG definitions from EFS, evaluating schedules, and queuing tasks to SQS), the Webserver (a dedicated Fargate container serving the Airflow UI from RDS PostgreSQL), a Celery Worker (an always-on Fargate container picking tasks off the SQS queue and spawning execution containers), the Ephemeral ECS Task (a short-lived Fargate container created per DAG run that mounts shared EFS, executes in complete isolation, then terminates), EFS (the shared backbone — all containers mount the same volume so a git push is immediately visible with no deployment step), RDS PostgreSQL (Airflow\'s metadata database storing DAG definitions, task states, and run history), SQS (the task queue between Scheduler and Celery Worker with no broker infrastructure to maintain), DynamoDB (distributed locking preventing duplicate task execution across concurrent containers), and the DAG Factory (a code layer watching the /dags directory for YAML files and generating valid Airflow DAGs at parse time).',
    challenges: [
      'Decomposing a monolithic single-EC2 Airflow into isolated ECS Fargate containers without downtime',
      'Designing ephemeral per-DAG-run execution containers that mount shared EFS without state leaks',
      'Implementing distributed locking via DynamoDB to prevent duplicate task execution across concurrent containers',
      'Building a YAML-driven DAG factory so analysts could ship pipelines without writing Airflow Python code',
      'Eliminating manual scaling and weekly crashes under bursty ELT workloads',
    ],
    outcomes: [
      { value: '60%+', label: 'Cost reduction' },
      { value: '7 → 3', label: 'Days to new pipeline' },
      { value: '0', label: 'Shared resources per run' },
      { value: 'Auto', label: 'Scaling per DAG' },
      { value: 'Weekly → 0', label: 'Crashes eliminated' },
      { value: '1', label: 'Container per component' },
    ],
    nodes: [
      { x: 10, y: 10, label: 'Git', w: 25 },
      { x: 50, y: 25, label: 'EFS', w: 25 },
      { x: 90, y: 10, label: 'Sched', w: 28 },
      { x: 90, y: 40, label: 'Worker', w: 30 },
      { x: 130, y: 25, label: 'ECS Task', w: 35 },
    ],
    edges: [
      { x1: 35, y1: 17, x2: 50, y2: 32 },
      { x1: 75, y1: 32, x2: 90, y2: 17 },
      { x1: 75, y1: 32, x2: 90, y2: 47 },
      { x1: 120, y1: 17, x2: 130, y2: 32 },
      { x1: 120, y1: 47, x2: 130, y2: 32 },
    ],
    diagram: {
      groups: [
        { x: 5, y: 20, w: 130, h: 260, label: 'ENGINEERS & ANALYSTS' },
        { x: 145, y: 20, w: 100, h: 260, label: 'EFS (SHARED)' },
        { x: 255, y: 20, w: 170, h: 260, label: 'AIRFLOW · ECS FARGATE' },
        { x: 435, y: 20, w: 140, h: 260, label: 'TASK EXECUTION' },
        { x: 585, y: 20, w: 205, h: 260, label: 'MANAGED STATE' },
      ],
      nodes: [
        { x: 15, y: 70, w: 110, h: 30, label: 'Python DAG', sublabel: 'git push' },
        { x: 15, y: 130, w: 110, h: 30, label: 'YAML file', sublabel: 'dag factory' },
        { x: 155, y: 100, w: 80, h: 60, label: '/dags', sublabel: 'mounted by all' },
        { x: 265, y: 50, w: 100, h: 30, label: 'Scheduler', sublabel: 'Fargate' },
        { x: 265, y: 110, w: 100, h: 30, label: 'Webserver', sublabel: 'Fargate' },
        { x: 265, y: 170, w: 100, h: 30, label: 'Celery Worker', sublabel: 'always-on' },
        { x: 445, y: 100, w: 120, h: 50, label: 'ECS Fargate Task', sublabel: 'ephemeral · per DAG run' },
        { x: 595, y: 50, w: 100, h: 30, label: 'RDS Postgres', sublabel: 'metadata DB' },
        { x: 595, y: 110, w: 100, h: 30, label: 'SQS', sublabel: 'Celery broker' },
        { x: 595, y: 170, w: 100, h: 30, label: 'DynamoDB', sublabel: 'distributed lock' },
        { x: 710, y: 50, w: 70, h: 30, label: 'Airflow UI', sublabel: '' },
      ],
      edges: [
        { x1: 125, y1: 85, x2: 155, y2: 115, label: 'git push' },
        { x1: 125, y1: 145, x2: 155, y2: 135, label: 'YAML' },
        { x1: 235, y1: 120, x2: 265, y2: 65, label: '' },
        { x1: 235, y1: 125, x2: 265, y2: 125, label: '' },
        { x1: 235, y1: 130, x2: 265, y2: 185, label: '' },
        { x1: 365, y1: 65, x2: 595, y2: 65, dashed: true, label: 'meta' },
        { x1: 365, y1: 125, x2: 595, y2: 125, label: 'queue' },
        { x1: 365, y1: 185, x2: 445, y2: 120, label: 'spawn' },
        { x1: 195, y1: 160, x2: 445, y2: 130, dashed: true, label: 'mount /dags' },
        { x1: 365, y1: 60, x2: 595, y2: 185, dashed: true, label: 'lock' },
        { x1: 505, y1: 140, x2: 595, y2: 185, dashed: true, label: 'lock' },
        { x1: 365, y1: 125, x2: 595, y2: 65, dashed: true, label: '' },
        { x1: 695, y1: 65, x2: 710, y2: 65, label: '' },
      ],
    },
  },
  {
    title: 'MadeiraMadeira — CDC Streaming Pipeline to Data Lake',
    description: 'Real-time Change Data Capture pipeline streaming every insert, update, and delete from MySQL, PostgreSQL, and MongoDB into a unified S3 data lake via Debezium, Kafka, and Apache Hudi — replacing nightly batch dumps with near-real-time eventual consistency.',
    input: 'MySQL, Postgres, MongoDB',
    throughput: 'Row-level CDC',
    latency: 'Near real-time',
    status: 'Production',
    stack: ['Debezium', 'Kafka Connect', 'Apache Kafka', 'Apache Spark', 'Apache Hudi', 'S3', 'Parquet'],
    image: PROJECT_IMAGE,
    overview: 'A real-time Change Data Capture pipeline that streams every insert, update, and delete from operational databases — relational (MySQL/PostgreSQL) and document (MongoDB) — into a unified data lake on S3, without impacting production database performance. Before this, data reached the lake through nightly batch exports, meaning analytics always worked with day-old data and any reprocessing required full table dumps. The CDC approach captures changes at the database log level, making the data lake eventually consistent with production in near real-time. The pipeline works across five stages: Source capture (Debezium connectors tap directly into database replication mechanisms — binary log for MySQL/PostgreSQL and native change streams for MongoDB — publishing every row-level change as a structured event to a Kafka topic), Transport (Apache Kafka holds the full stream of change events, decoupling capture from storage, allowing multiple consumers, and providing a replay buffer if downstream systems fall behind), the Bronze layer (a Kafka S3 Sink Connector continuously flushes raw CDC events to S3 as the unmodified record of every change, serving as the replay source if transformations need to be rerun), the Gold layer (Spark Structured Streaming reads from Kafka topics, applies transformations including deduplication, schema evolution, and upsert semantics, and writes results into Apache Hudi tables on S3), and Apache Hudi (chosen because CDC data is inherently mutable — Hudi provides upsert support, time-travel queries, and incremental read APIs, meaning a DELETE in production becomes a correct soft delete in the lake, and UPDATE events are merged by primary key rather than appended as duplicates).',
    challenges: [
      'Capturing row-level changes from heterogeneous sources (MySQL binlog, Postgres WAL, MongoDB change streams) under a unified event model',
      'Implementing correct upsert/delete semantics in the lake — Hudi MERGE by primary key instead of appending duplicates',
      'Decoupling capture from storage so downstream failures or replay don\'t impact production databases',
      'Handling schema evolution across CDC streams without breaking downstream Hudi tables',
      'Providing incremental/time-travel queries so consumers can ask "what changed since timestamp X" without full table scans',
    ],
    outcomes: [
      { value: 'Near RT', label: 'Lake freshness vs nightly' },
      { value: '3', label: 'Source DB types unified' },
      { value: 'Bronze+Gold', label: 'Medallion layers' },
      { value: 'Full', label: 'Replay buffer (Kafka)' },
      { value: '0', label: 'Production DB impact' },
      { value: 'Hudi', label: 'Upsert + time-travel' },
    ],
    nodes: [
      { x: 10, y: 10, label: 'DBs', w: 25 },
      { x: 50, y: 10, label: 'Debez', w: 30 },
      { x: 95, y: 10, label: 'Kafka', w: 28 },
      { x: 95, y: 40, label: 'S3 raw', w: 30 },
      { x: 140, y: 25, label: 'Hudi', w: 28 },
    ],
    edges: [
      { x1: 35, y1: 17, x2: 50, y2: 17 },
      { x1: 80, y1: 17, x2: 95, y2: 17 },
      { x1: 125, y1: 17, x2: 140, y2: 28 },
      { x1: 95, y1: 47, x2: 140, y2: 32, dashed: true },
      { x1: 109, y1: 22, x2: 140, y2: 25 },
    ],
    diagram: {
      groups: [
        { x: 5, y: 20, w: 110, h: 260, label: 'SOURCE DATABASES' },
        { x: 125, y: 20, w: 120, h: 260, label: 'CDC LAYER (DEBEZIUM)' },
        { x: 255, y: 20, w: 110, h: 260, label: 'APACHE KAFKA' },
        { x: 375, y: 20, w: 120, h: 120, label: 'BRONZE · S3' },
        { x: 375, y: 160, w: 120, h: 120, label: 'GOLD · SPARK STREAMING' },
        { x: 505, y: 20, w: 285, h: 260, label: 'DATA LAKE — APACHE HUDI ON S3' },
      ],
      nodes: [
        { x: 15, y: 70, w: 90, h: 35, label: 'MySQL / Postgres', sublabel: 'binlog / WAL' },
        { x: 15, y: 180, w: 90, h: 35, label: 'MongoDB', sublabel: 'change streams' },
        { x: 135, y: 70, w: 100, h: 35, label: 'SQL Connector', sublabel: 'Debezium' },
        { x: 135, y: 180, w: 100, h: 35, label: 'MongoDB Connector', sublabel: 'Debezium' },
        { x: 265, y: 110, w: 90, h: 60, label: 'CDC Topics', sublabel: 'insert · update · delete' },
        { x: 385, y: 50, w: 100, h: 35, label: 'Raw CDC Events', sublabel: 'S3 Sink · Parquet' },
        { x: 385, y: 190, w: 100, h: 35, label: 'Transformations', sublabel: 'dedup · upsert' },
        { x: 525, y: 90, w: 120, h: 70, label: 'Hudi Tables', sublabel: 'upsert · time-travel' },
        { x: 670, y: 60, w: 105, h: 30, label: 'Incremental Read', sublabel: 'since timestamp X' },
        { x: 670, y: 110, w: 105, h: 30, label: 'Time-Travel Q', sublabel: 'history' },
        { x: 670, y: 160, w: 105, h: 30, label: 'Analytics', sublabel: 'BI / ML' },
      ],
      edges: [
        { x1: 105, y1: 87, x2: 135, y2: 87, label: 'binlog' },
        { x1: 105, y1: 197, x2: 135, y2: 197, label: 'change stream' },
        { x1: 235, y1: 87, x2: 265, y2: 120, label: '' },
        { x1: 235, y1: 197, x2: 265, y2: 165, label: '' },
        { x1: 355, y1: 125, x2: 385, y2: 67, label: 'S3 Sink' },
        { x1: 355, y1: 160, x2: 385, y2: 205, label: 'readStream' },
        { x1: 485, y1: 207, x2: 525, y2: 145, label: 'MERGE INTO' },
        { x1: 435, y1: 85, x2: 525, y2: 130, dashed: true, label: 'replay' },
        { x1: 645, y1: 125, x2: 670, y2: 75, label: '' },
        { x1: 645, y1: 130, x2: 670, y2: 125, label: '' },
        { x1: 645, y1: 145, x2: 670, y2: 175, label: '' },
      ],
    },
  },
  {
    title: 'McGraw Hill — Cluster Autopilot',
    description: 'Automated Databricks cluster optimization system that continuously collects runtime metrics from every job, analyzes them over a window calibrated to each job\'s schedule, and applies the right cluster configuration and Spark tuning parameters — without human intervention. Saved over 30% of Databricks costs across 300+ jobs.',
    input: 'Databricks Jobs',
    throughput: '300+ jobs',
    latency: 'Schedule-based',
    status: 'Production',
    stack: ['Databricks', 'Apache Spark', 'Delta Lake', 'S3', 'New Relic', 'Python', 'Databricks Jobs API', 'Bash (init scripts)'],
    image: PROJECT_IMAGE,
    overview: 'Built Cluster Autopilot to replace manual cluster configuration guesswork with evidence-based optimization. Before, teams picked safe, large clusters at job creation and never had the data to justify downsizing — leading to systematic over-provisioning. An init script attached to every Databricks cluster ships cluster metrics (CPU, memory, GC, executor count) and Spark metrics (shuffle read/write, spill, task skew, peak execution memory) to both New Relic (real-time monitoring) and S3 (persisted as a Delta table for historical analysis). The engine then aggregates metrics over a window tied to each job\'s schedule — 7 days for daily jobs, 30 days for weekly jobs — before issuing recommendations. It determines over/under-provisioning, selects the best instance family (compute-optimized vs memory-optimized), tunes Spark partitioning and executor memory based on skew and GC pressure, and performs seasonal analysis to pre-configure clusters for predictable spikes. Recommendations are auto-applied via the Databricks Jobs API.',
    challenges: [
      'Collecting two categories of runtime metrics (cluster + Spark) from every job via an init script without impacting job performance',
      'Calibrating the aggregation window to each job\'s schedule — 7 days for daily, 30 days for weekly — to capture natural variance without reacting to outliers',
      'Selecting the right instance family per workload instead of defaulting to general-purpose for everything',
      'Detecting data skew from p50 vs p99 task duration and recommending salting or repartitioning strategies',
      'Using seasonal analysis on the Delta history to pre-configure clusters for predictable spikes (month-end, quarter-end, campaigns)',
    ],
    outcomes: [
      { value: '> 30%', label: 'Databricks cost reduction' },
      { value: '300+', label: 'Jobs optimized' },
      { value: '7 / 30', label: 'Day windows (daily / weekly)' },
      { value: 'Auto', label: 'Config applied via API' },
      { value: '2', label: 'Metric sinks (NR + S3)' },
      { value: '0', label: 'Manual tuning needed' },
    ],
    nodes: [
      { x: 10, y: 15, label: 'Jobs', w: 25 },
      { x: 50, y: 15, label: 'Init', w: 25 },
      { x: 95, y: 10, label: 'NR', w: 22 },
      { x: 95, y: 30, label: 'S3', w: 22 },
      { x: 140, y: 20, label: 'Engine', w: 30 },
      { x: 185, y: 20, label: 'Apply', w: 25 },
    ],
    edges: [
      { x1: 35, y1: 22, x2: 50, y2: 22 },
      { x1: 75, y1: 22, x2: 95, y2: 17 },
      { x1: 75, y1: 22, x2: 95, y2: 37 },
      { x1: 117, y1: 37, x2: 140, y2: 27 },
      { x1: 170, y1: 27, x2: 185, y2: 27 },
      { x1: 185, y1: 32, x2: 22, y2: 22, dashed: true },
    ],
    diagram: {
      groups: [
        { x: 5, y: 20, w: 100, h: 260, label: 'COLLECTION · INIT SCRIPT' },
        { x: 115, y: 20, w: 130, h: 260, label: 'STORAGE & MONITORING' },
        { x: 255, y: 20, w: 170, h: 260, label: 'OPTIMIZATION ENGINE' },
        { x: 435, y: 20, w: 140, h: 260, label: 'AUTO-APPLY · JOBS API' },
        { x: 585, y: 20, w: 205, h: 260, label: 'DATABRICKS · 300+ JOBS' },
      ],
      nodes: [
        { x: 15, y: 60, w: 80, h: 35, label: 'Cluster Metrics', sublabel: 'CPU · Mem · GC' },
        { x: 15, y: 130, w: 80, h: 35, label: 'Spark Metrics', sublabel: 'Shuffle · Spill · Skew' },
        { x: 15, y: 200, w: 80, h: 35, label: 'Init Script', sublabel: 'fires on startup' },
        { x: 125, y: 60, w: 110, h: 35, label: 'New Relic', sublabel: 'real-time alerts' },
        { x: 125, y: 170, w: 110, h: 35, label: 'S3 → Delta Table', sublabel: 'historical per job' },
        { x: 265, y: 50, w: 150, h: 35, label: 'Metric Aggregation', sublabel: '7d daily · 30d weekly' },
        { x: 265, y: 110, w: 150, h: 35, label: 'Cluster Sizing', sublabel: 'instance family fit' },
        { x: 265, y: 170, w: 150, h: 35, label: 'Spark Tuning', sublabel: 'partitions · skew · mem' },
        { x: 265, y: 225, w: 150, h: 30, label: 'Seasonal Analysis', sublabel: 'spike pre-config' },
        { x: 445, y: 80, w: 120, h: 35, label: 'Cluster Config', sublabel: 'instance · workers' },
        { x: 445, y: 170, w: 120, h: 35, label: 'Spark Config', sublabel: 'partitions · memory' },
        { x: 595, y: 110, w: 110, h: 60, label: 'Databricks Jobs', sublabel: '300+ · auto-updated' },
        { x: 725, y: 125, w: 60, h: 35, label: 'Cost', sublabel: '-30%' },
      ],
      edges: [
        { x1: 95, y1: 78, x2: 125, y2: 78, label: '' },
        { x1: 95, y1: 148, x2: 125, y2: 78, label: '' },
        { x1: 95, y1: 78, x2: 125, y2: 188, label: '' },
        { x1: 95, y1: 148, x2: 125, y2: 188, label: '' },
        { x1: 180, y1: 78, x2: 265, y2: 68, label: 'alert', dashed: true },
        { x1: 235, y1: 188, x2: 265, y2: 68, label: 'query' },
        { x1: 265, y1: 85, x2: 265, y2: 110, label: '' },
        { x1: 340, y1: 85, x2: 340, y2: 170, label: '' },
        { x1: 340, y1: 85, x2: 340, y2: 240, label: '' },
        { x1: 415, y1: 128, x2: 445, y2: 98, label: '' },
        { x1: 415, y1: 188, x2: 445, y2: 188, label: '' },
        { x1: 415, y1: 240, x2: 445, y2: 98, label: '' },
        { x1: 565, y1: 98, x2: 595, y2: 125, label: 'POST update' },
        { x1: 565, y1: 188, x2: 595, y2: 140, label: 'POST update' },
        { x1: 705, y1: 140, x2: 725, y2: 142, label: '' },
      ],
    },
  },
  {
    title: 'McGraw Hill — Spark Performance Agent',
    description: 'An AI-powered agent that autonomously analyzes Databricks job performance every week, identifies the worst-performing jobs, and delivers actionable optimization reports with code-level recommendations directly to the team that owns each job — surfacing issues no cluster resize can fix.',
    input: 'Delta Table + Spark Plans',
    throughput: 'Top 5 jobs / week',
    latency: 'Weekly run',
    status: 'Production',
    stack: ['Databricks', 'Apache Spark', 'Delta Lake', 'Python', 'LLM (GPT)', 'Slack API', 'FastAPI', 'React'],
    image: PROJECT_IMAGE,
    overview: 'Where Cluster Autopilot handles infrastructure decisions automatically, the Performance Agent handles the harder problem: helping engineers write better Spark code. It surfaces issues that no cluster resize can fix — cartesian joins, missing predicate pushdowns, data skew — and explains exactly what to change and why, in plain language. The agent reads from the same Delta table populated by the init script (CPU, memory, shuffle, spill, task skew, peak memory per job run) and from Spark query plans collected at runtime. Both are required: metrics tell you *that* something is wrong, query plans tell you *why*. Each week, the agent scores every job\'s last executions across key signals — disk spill, task duration skew, GC pressure, and overall runtime — and selects the top 5 worst performers to keep the report focused and avoid alert fatigue. The query plan for each flagged job is parsed to detect known anti-patterns (cartesian joins, missing predicate pushdowns, data skew). The aggregated metrics and detected plan issues are then sent to an LLM, which produces a narrative explanation and concrete recommendations grounded in the specific metrics and plan of that job — not generic advice. Each job gets its own hosted report page showing metric trends over time, plan issues found, Spark tuning suggestions, and code-level change examples. Every week, the job owner receives a Slack message with a direct link to the report and a one-line summary of the key finding.',
    challenges: [
      'Combining runtime metrics with Spark query plans — metrics tell you that something is wrong, plans tell you why',
      'Ranking jobs weekly across spill, skew, GC pressure, and runtime to surface only the top 5 worst performers and avoid alert fatigue',
      'Parsing query plans to detect anti-patterns: cartesian joins, missing predicate pushdowns, and data skew from partition imbalance',
      'Grounding LLM recommendations in the specific metrics and plan of each job rather than producing generic Spark advice',
      'Building a persistent, linkable per-job report page with metric trends, plan issues, and code-level change examples',
    ],
    outcomes: [
      { value: 'Weekly', label: 'Autonomous analysis' },
      { value: 'Top 5', label: 'Worst jobs per run' },
      { value: '3', label: 'Anti-patterns detected' },
      { value: 'LLM', label: 'Code-level recs' },
      { value: 'Slack', label: 'Owner notification' },
      { value: '1', label: 'Report page per job' },
    ],
    nodes: [
      { x: 10, y: 10, label: 'Delta', w: 28 },
      { x: 10, y: 35, label: 'Plans', w: 28 },
      { x: 55, y: 10, label: 'Rank', w: 25 },
      { x: 55, y: 35, label: 'Analyze', w: 30 },
      { x: 100, y: 22, label: 'LLM', w: 22 },
      { x: 140, y: 10, label: 'Report', w: 30 },
      { x: 140, y: 35, label: 'Slack', w: 25 },
    ],
    edges: [
      { x1: 38, y1: 18, x2: 55, y2: 18 },
      { x1: 38, y1: 42, x2: 55, y2: 42 },
      { x1: 80, y1: 18, x2: 100, y2: 27 },
      { x1: 85, y1: 42, x2: 100, y2: 27 },
      { x1: 122, y1: 27, x2: 140, y2: 18 },
      { x1: 122, y1: 27, x2: 140, y2: 42 },
    ],
    diagram: {
      groups: [
        { x: 5, y: 20, w: 130, h: 260, label: 'DATA SOURCES' },
        { x: 145, y: 20, w: 180, h: 260, label: 'PERFORMANCE AGENT · WEEKLY RUN' },
        { x: 335, y: 20, w: 180, h: 260, label: 'LLM ANALYSIS' },
        { x: 525, y: 20, w: 145, h: 260, label: 'REPORT · HOSTED WEB APP' },
        { x: 680, y: 20, w: 110, h: 260, label: 'NOTIFICATION' },
      ],
      nodes: [
        { x: 15, y: 60, w: 110, h: 35, label: 'Delta Table', sublabel: 'metrics per job run' },
        { x: 15, y: 140, w: 110, h: 35, label: 'Spark Query Plans', sublabel: 'collected at runtime' },
        { x: 15, y: 210, w: 110, h: 35, label: 'Init Script Data', sublabel: 'shared with Autopilot' },
        { x: 155, y: 50, w: 160, h: 35, label: 'Job Ranker', sublabel: 'top 5 worst (spill · skew · GC)' },
        { x: 155, y: 120, w: 160, h: 35, label: 'Plan Analyzer', sublabel: 'cartesian · pushdown · skew' },
        { x: 155, y: 190, w: 160, h: 35, label: 'Aggregation', sublabel: 'metrics + plan issues' },
        { x: 345, y: 90, w: 160, h: 50, label: 'LLM', sublabel: 'narrative + code-level recs' },
        { x: 345, y: 170, w: 160, h: 35, label: 'Grounding Context', sublabel: 'specific metrics + plan' },
        { x: 535, y: 60, w: 125, h: 35, label: 'Per-Job Page', sublabel: 'metric trends' },
        { x: 535, y: 130, w: 125, h: 35, label: 'Plan Issues', sublabel: 'anti-patterns found' },
        { x: 535, y: 200, w: 125, h: 35, label: 'Code Examples', sublabel: 'tuning + restructure' },
        { x: 690, y: 90, w: 90, h: 50, label: 'Slack Alert', sublabel: 'weekly · to owner' },
        { x: 690, y: 180, w: 90, h: 35, label: 'Report Link', sublabel: 'direct URL' },
      ],
      edges: [
        { x1: 125, y1: 78, x2: 155, y2: 68, label: '' },
        { x1: 125, y1: 158, x2: 155, y2: 138, label: '' },
        { x1: 125, y1: 228, x2: 155, y2: 208, label: '' },
        { x1: 315, y1: 68, x2: 345, y2: 105, label: 'top 5' },
        { x1: 315, y1: 138, x2: 345, y2: 115, label: 'anti-patterns' },
        { x1: 315, y1: 208, x2: 345, y2: 120, label: '' },
        { x1: 425, y1: 140, x2: 535, y2: 78, label: '' },
        { x1: 425, y1: 140, x2: 535, y2: 148, label: '' },
        { x1: 425, y1: 140, x2: 535, y2: 218, label: '' },
        { x1: 660, y1: 78, x2: 690, y2: 105, label: '' },
        { x1: 660, y1: 148, x2: 690, y2: 115, label: '' },
        { x1: 660, y1: 218, x2: 690, y2: 197, label: '' },
      ],
    },
  },
];